# Generated by Django 4.2 on 2023-04-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nifty_stocks_equitysymbol_linked_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitysymbol',
            name='linked_stocks',
        ),
        migrations.DeleteModel(
            name='Nifty_Stocks',
        ),
    ]
